### ISSUE TITLE
license of node-build 0.1.4

### ISSUE THREAD

**Issue by luisapace** [jonlb/node-build#6]
Hi, my team would like to use the package node-build 0.1.4 and to approve that I've to verify all its licenses.

Could you please tell me what is the license of node-build 0.1.4? 

Many thanks.

**Comment by hrieke** [comment]
Likewise here.
Could you please specify a license that your code is released under?

**Comment by jonlb** [comment]
I have added a license file but please note that this does NOT mean I will be maintaining this software. If you want to use it you can feel free to fork it for your own use.

**Comment by hrieke** [comment]
Thank you for doing this; unsupported is understood.
